### ISSUE TITLE
Port/migrate all DaisySP examples to examples for Arduino

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/ArduinoDaisySP#1]
Biggest differences is the interleaved vs non-interleaved callbacks (which libdaisy will likely be moving towards as well).

`void callback(float **in, float **out, size_t size);`

Where `**in` and `**out` are pointers to 2d arrays: `buffer[NUM_CHANNELS][NUM_SAMPLES]`

There are a few examples in the repo already to use as a reference.

----

Ideally this would be a script or something that gets you most of the way there (because we'll always be adding more examples to the DaisySP library, and having a quick way to migrate examples to Arduino would be a huge time-saver in the long run.

**Comment by beserge** [comment]
All work except pluck

**Comment by stephenhensley** [comment]
Alright, here are my batch notes:

# Test Notes for examples

## All

Go through and clean up formatting, lots of tab/space inconsistencies.

## Adenv

sig undefined, and no Adenv usage.

## bypass 

missing 'chn' for loop

## nlfilt

you'll want to fill the entire `dry[]` buffer before processing it in the nlfilt.

right now it looks like you're processing the `dry[]` buffer for each sample. 

I know this one is confusing, I just originally had it setup for doing block processing instead of single-sample processing. So that's the issue.

## osc

chn not defined, no oscillator object.

## pluck

**I fixed this one already with my other regex fixes**

init_buff needed to be a global object

realistically we can/should migrate that buffer inside the object at some point.

In an earlier version of the code you could fill it with the impulse yourself (different init buffers would have different timbres). But now it initializes it internally.

## reverbsc/svf

Lets take out the:

`out[chn][i] = (chn % 2) == 0 ? filt.Low() : filt.High();` and equivalent in reverbsc

I actually really like this, and its a witty way to assign 2 || 4 channels with no code change

BUT its not very easy to read.

I'd rather just handle the first two channels in all of these examples, and then have a few quad audio examples in the ArduinoAudio repo to show doing quad on the Patch hardware.

(I'm going to go through and change all of these to DAISY_SEED anyway so that they don't try to use the external codec at all).

maybe double check other examples for this while cleaning up the tabs and stuff.

## template

things like 'passthru, bypass, etc. are already good starting points. Lets just get rid of this one.

**Comment by stephenhensley** [comment]
oh actually, I fixed the osc when I readded my oscillator/stereo delay examples from master.
